move no-iaas tests into acceptance
- they are acceptance tests anyway, so this makes
sense.
- error if we are missing terraform binary path

Signed-off-by: Zach Gershman <zgershman@pivotal.io>

diff --git a/scripts/acceptance_tests b/scripts/acceptance_tests
--- a/scripts/acceptance_tests
+++ b/scripts/acceptance_tests
@@ -13,6 +13,11 @@ function main() {
   cleanup_terraform
   trap "cleanup_terraform" INT TERM EXIT
 
+  if [[ ! -f "${TERRAFORM_BINARY_PATH}" ]]; then
+    echo "missing required terraform binary path"
+    exit 127
+  fi
+
   local parallelFlag
   if [[ "${BBL_IAAS}" == "aws" ]]; then
     parallelFlag=""
